### ISSUE TITLE
一加7pro edxposed sandhook 闪退

### ISSUE THREAD

**Issue by uoox** [ohyeah521/HexinNoAds#1]
装此模块前正常使用，安装重启后，同花顺app闪退

**Comment by ohyeah521** [comment]
同花顺版本号是多少，是从GooglePlay下载的最新版本吗？

**Comment by ohyeah521** [comment]
同花顺至尊版v9.68.35 下载地址：
链接: https://pan.baidu.com/s/1xaE7tJHFCgw7JnxQwBz0uQ 提取码: ib8k

**Comment by uoox** [comment]
是的，play最新版 同花顺至尊版v9.68.35

**Comment by ohyeah521** [comment]
> 是的，play最新版 同花顺至尊版v9.68.35

更新一下新版本试试

**Comment by uoox** [comment]
从play下载的和从百度云下载的都会闪退，模块为最新

**Comment by ohyeah521** [comment]
> 从play下载的和从百度云下载的都会闪退，模块为最新
请提供崩溃日志，或者留个微信

**Comment by uoox** [comment]
录了个屏邮件发您了

**Comment by ohyeah521** [comment]
> 录了个屏邮件发您了

应该是第一次安装，同花顺没有初始化，导致的。
解决方法：
1、 你先禁用xposed插件，
2、 重启手机，运行同花顺，完成初始设置
3、 开启xposed 插件，重启手机
4、 顺利的话，应该解决了

**Comment by uoox** [comment]
不顺利T T

禁用重启后可以正常打开同花顺
开启重启后闪退

**Comment by ohyeah521** [comment]
> 不顺利T T
> 
> 禁用重启后可以正常打开同花顺
> 开启重启后闪退

把你之前安装的xposed插件卸载，安装这个调试版本的插件，重启手机，然后运行同花顺，崩溃后，打开xposed界面，日志，把日志内容fuzh复制出来，贴到这里，我看看是哪里导致崩溃的。
[app-release.zip](https://github.com/ohyeah521/HexinNoAds/files/3251569/app-release.zip)

**Comment by uoox** [comment]
这个其实一开始我有看啦，我刚刚试了edxposed installer和manager，发现他们都没有日志。。。

手机里面还有其他模块，都是可以用的，另外，我用的edxposed是sandhook 0.4.2.3

**Comment by madaono** [comment]
是否有针对太极阴做适配的计划呢？

**Comment by ohyeah521** [comment]
> 是否有针对太极阴做适配的计划呢？

我编译了一个太极的版本，请帮忙测试一下：
[app-release.zip](https://github.com/ohyeah521/HexinNoAds/files/3254797/app-release.zip)

**Comment by ohyeah521** [comment]
> 这个其实一开始我有看啦，我刚刚试了edxposed installer和manager，发现他们都没有日志。。。
> 
> 手机里面还有其他模块，都是可以用的，另外，我用的edxposed是sandhook 0.4.2.3


没有日志，我也没办法了，等周末我弄个edxposed环境测试一下吧

**Comment by madaono** [comment]
下载并安装之后发现太极跟面具都不能正确激活。。。

**Comment by madaono** [comment]
> > 是否有针对太极阴做适配的计划呢？
> 
> 我编译了一个太极的版本，请帮忙测试一下：
> [app-release.zip](https://github.com/ohyeah521/HexinNoAds/files/3254797/app-release.zip)

无法添加进太极，应该是太极有自己的模块验证方式，这个可以貌似也不能直接加载进magisk

**Comment by ohyeah521** [comment]
> > > 是否有针对太极阴做适配的计划呢？
> > 
> > 
> > 我编译了一个太极的版本，请帮忙测试一下：
> > [app-release.zip](https://github.com/ohyeah521/HexinNoAds/files/3254797/app-release.zip)
> 
> 无法添加进太极，应该是太极有自己的模块验证方式，这个可以貌似也不能直接加载进magisk

貌似是太极要审查，你可以在这里给太极提交新模块审核申请：
https://github.com/taichi-framework/TaiChi/issues

**Comment by uoox** [comment]
新版似乎不会闪退了，不过虽然有十档换level2的界面，却不显示数据，（只显示5档）

**Comment by ohyeah521** [comment]
十档，五百档都是服务器端做验证的，无解，其他功能可以用。

uoox <notifications@github.com> 于 2019年6月10日周一 22:36写道：
