### ISSUE TITLE
提供的同花顺在 一加5T 上闪退

### ISSUE THREAD

**Issue by VanDeAnna** [ohyeah521/HexinNoAds#4]
系统是 一加5T，beta 31，安卓 P
安装了 Magisk 19.3 Manager 7.2
Xposed 环境是 Riru Core v19 + EdXposed SandHook v0.4.2.3

按照 HexinNoAds 提示的网盘下载的 9.68.35 版本 同花顺，
无论是否安装 HexinNoAds
无论 Magisk 是否开启 Magisk Hide
都无法运行，点击同花顺应用之后直接闪退

**Comment by ohyeah521** [comment]
> EdXposed

有可能是和Riru Core v19 + EdXposed SandHook v0.4.2.3 不兼容，请提供logcat崩溃日志，否则我没有办法定位bug

**Comment by ohyeah521** [comment]
> 系统是 一加5T，beta 31，安卓 P
> 安装了 Magisk 19.3 Manager 7.2
> Xposed 环境是 Riru Core v19 + EdXposed SandHook v0.4.2.3
> 
> 按照 HexinNoAds 提示的网盘下载的 9.68.35 版本 同花顺，
> 无论是否安装 HexinNoAds
> 无论 Magisk 是否开启 Magisk Hide
> 都无法运行，点击同花顺应用之后直接闪退

这个问题已经解决了，请升级到最新版本即可。
