### ISSUE TITLE
貌似 lv2 无效？

### ISSUE THREAD

**Issue by kmvan** [ohyeah521/HexinNoAds#5]
![Screenshot_20190610-095434](https://user-images.githubusercontent.com/3839554/59167894-0a76e580-8b66-11e9-957f-6b1ac0e0fc83.jpg)

Android pie.

**Comment by ohyeah521** [comment]
这个数据是网络严重，没法破解，核心数据在服务器端进行校验，部分l2功能是本地校验的，这样的功能可以使用

Km.Van <notifications@github.com> 于 2019年6月10日周一 09:57写道：

**Comment by kmvan** [comment]
明白了
